# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'')),
                ('date', models.DateField()),
                ('content', models.TextField(default=b'')),
                ('tldr', models.TextField(default=b'')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skribblr.Author')),
            ],
        ),
    ]
